### PR TITLE
Remove `isOtherLowercase` and `isOtherUppercase` from the `Character` models

### PR DESCRIPTION
**Pull request by NlightNFotis**
These were removed in upstream commit https://github.com/openjdk/jdk/pull/2846/files
and are now creating problems when trying to build the models library with openJDK-17.

### CODE REVIEW

**Review by peterschrammel — COMMENTED** [review]
That's a legitmate simplification as the called method has never been modelled.
To be coherent with other changes to JDK files, please comment out the code instead of removing it and put a comment above it that explains why the code has been commented out.

**Comment by NlightNFotis** [comment]
Hello @peterschrammel.

I have implemented the changes you suggested.

I'm assuming Travis is dead (or our config is super-broken); does this mean you have to merge manually?

**Comment by peterschrammel** [comment]
Can you add a simple github actions configuration to replace it?

**Comment by NlightNFotis** [comment]
Hi @peterschrammel, yes, absolutely.

I will spin one and rebase the current PR on top of the branch that contains it.

**Comment by NlightNFotis** [comment]
Okay, @peterschrammel, a basic config for CI has been added.

We could expand it to a more featureful array of platforms/environments, but it can also be done as a later step. What would be your preference?

**Review by peterschrammel — APPROVED** [review]
One platform is sufficient for now.

**Comment by NlightNFotis** [comment]
Alright @peterschrammel.

The travis configuration will need to be removed from the Repository's settings as a required check as well, I believe, and then I should be able to merge.

**Comment by peterschrammel** [comment]
Should be ready now.

**Pull request merged**
